### ISSUE TITLE
IP in postorius email instead of configured SERVE_FROM_DOMAIN

### ISSUE THREAD

**Issue by omnitec** [maxking/docker-mailman#488] opened 2021-08-16 22:09 UTC
Given the web/settings_local.py domain setting:

SERVE_FROM_DOMAIN='aaa.bbb.org'

Why does Postorius only provide the IP in  user emails:

    https://172.18.0.15:8000/

**Comment by maxking** [comment] 2021-08-17 17:21
Which web server are you using?

You probably want to make sure that you are setting these headers in whichever proxy server you are using (Ningx, Apache2 or something else)

```
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $remote_addr;
```

**Comment by omnitec** [comment] 2021-08-17 19:25
Ahh, .. none? Emails sent from Postorius do not transit the web server, .. they forward to postfix on host port 25 to relay.

What must be done to convince Postorius to use SERVE_FROM_DOMAIN?

**Comment by omnitec** [comment] 2021-08-30 23:45
Fixed the web container crash by removing the ' ' around the FQDN in the compose file:

mailman-web     | Setting sub.comain.org as the default domain ...

.. but the password reset email still has the container IP:Port instead of a usable link.

Is this a bug, or is something missing?

**Comment by maxking** [comment] 2021-08-31 00:41
Which web server are you using and can you post the configuration for the web server here?

**Comment by omnitec** [comment] 2021-08-31 00:45
Outbound emails do not route through a webserver, .. don't understand the question??

The bad links are in the emails sent by Postorius, e.g. to recover a password.

**Comment by maxking** [comment] 2021-08-31 00:56
Yes, but the routing of the email has really nothing to do with how the email's content is generated. IIUC, the problem is in the content of the URL which is generated when a user visits Postorius using some URL. 

Postorius can potentially be served from more than a single domain, the "current" site is determined by `SITE_ID` setting, but also using the `Host` header in the incoming request to Postorius. The generated email uses the `Host` from that request, hence my question about what your webeserver configuration is.

With reverse proxies, if the `Host` header isn't set to what the incoming request had, Postorius will see the `Host` as the URL at which web server reverse proxied, so basically the IP:PORT of the container is used as it can't do anything better.

**Comment by omnitec** [comment] 2021-08-31 01:02
Ahh, .. that sounds like the problem! The loadbalancer in front of the mailman configuration is passing to the internal IP:port, .. so Postorius would see that in the Host URL.

How can Postorius be convinced to use, say, SERVE_FROM_DOMAIN instead of the Host header as described in the docs:

SERVE_FROM_DOMAIN: The domain name from which Django will be served. To be added to ALLOWED_HOSTS in django settings. Default value is not set. This also replaces Django's default example.com SITE and becomes the default SITE (with SITE_ID=1).

    Thanks!!

**Comment by maxking** [comment] 2021-08-31 16:50
Django's SITE framework actually allows using both SITE_ID and Hosts, but for some reason the package we use for Mailman relies on Host header, not sure what is up with that. I'll see if there is a way to actually force it to use SITE_ID, but so far, I don't know without going through the code of django-allauth.

**Comment by omnitec** [comment] 2021-08-31 17:40
GOT IT!!!

Tweaking the host header was straightforward by adding to the nginx config:

proxy_set_header Host "host.sub.domain.org";

Adding host.sub.comain.org to ALLOWED_HOSTS and DJANGO_ALLOWED_HOSTS was then required.

    THANKS!!

**Comment by maxking** [comment] 2021-08-31 17:45
Oh i thought you weren't using Ningx and something else like Kubernetes bases solution.

I already mentioned proxy_set_header up in the messages.

Glad you got it sorted out, closing this ticket.

**Closed by maxking** 2021-08-31 17:45 UTC
